version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./server:/app
    command: npm run start-dev

  client:
    build: ./client
    ports:
      - "1234:1234"
    volumes:
      - ./client:/app
    command: npm start
